// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/expense/expense.proto

package expense

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SplitType defines how an expense is split
type SplitType int32

const (
	SplitType_EQUAL      SplitType = 0
	SplitType_EXACT      SplitType = 1
	SplitType_PERCENTAGE SplitType = 2
)

// Enum value maps for SplitType.
var (
	SplitType_name = map[int32]string{
		0: "EQUAL",
		1: "EXACT",
		2: "PERCENTAGE",
	}
	SplitType_value = map[string]int32{
		"EQUAL":      0,
		"EXACT":      1,
		"PERCENTAGE": 2,
	}
)

func (x SplitType) Enum() *SplitType {
	p := new(SplitType)
	*p = x
	return p
}

func (x SplitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_expense_expense_proto_enumTypes[0].Descriptor()
}

func (SplitType) Type() protoreflect.EnumType {
	return &file_proto_expense_expense_proto_enumTypes[0]
}

func (x SplitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitType.Descriptor instead.
func (SplitType) EnumDescriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{0}
}

// Split represents how much each user owes
type Split struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Split) Reset() {
	*x = Split{}
	mi := &file_proto_expense_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Split) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Split) ProtoMessage() {}

func (x *Split) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Split.ProtoReflect.Descriptor instead.
func (*Split) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{0}
}

func (x *Split) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Split) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Expense represents a shared expense
type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidBy        string                 `protobuf:"bytes,4,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	SplitType     SplitType              `protobuf:"varint,5,opt,name=split_type,json=splitType,proto3,enum=expense.SplitType" json:"split_type,omitempty"`
	Splits        []*Split               `protobuf:"bytes,6,rep,name=splits,proto3" json:"splits,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_proto_expense_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{1}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Expense) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Expense) GetPaidBy() string {
	if x != nil {
		return x.PaidBy
	}
	return ""
}

func (x *Expense) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_EQUAL
}

func (x *Expense) GetSplits() []*Split {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *Expense) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Balance represents amount owed between two users
type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_proto_expense_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{2}
}

func (x *Balance) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Balance) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Balance) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// CreateExpenseRequest creates a new expense
type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidBy        string                 `protobuf:"bytes,3,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	SplitType     SplitType              `protobuf:"varint,4,opt,name=split_type,json=splitType,proto3,enum=expense.SplitType" json:"split_type,omitempty"`
	Splits        []*Split               `protobuf:"bytes,5,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{3}
}

func (x *CreateExpenseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExpenseRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateExpenseRequest) GetPaidBy() string {
	if x != nil {
		return x.PaidBy
	}
	return ""
}

func (x *CreateExpenseRequest) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_EQUAL
}

func (x *CreateExpenseRequest) GetSplits() []*Split {
	if x != nil {
		return x.Splits
	}
	return nil
}

// CreateExpenseResponse returns the created expense
type CreateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{4}
}

func (x *CreateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

// GetExpenseRequest requests an expense by ID
type GetExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseRequest) Reset() {
	*x = GetExpenseRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseRequest) ProtoMessage() {}

func (x *GetExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseRequest.ProtoReflect.Descriptor instead.
func (*GetExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{5}
}

func (x *GetExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

// GetExpenseResponse returns the requested expense
type GetExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseResponse) Reset() {
	*x = GetExpenseResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseResponse) ProtoMessage() {}

func (x *GetExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseResponse.ProtoReflect.Descriptor instead.
func (*GetExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{6}
}

func (x *GetExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

// ListExpensesRequest lists expenses for a user
type ListExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesRequest) Reset() {
	*x = ListExpensesRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesRequest) ProtoMessage() {}

func (x *ListExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesRequest.ProtoReflect.Descriptor instead.
func (*ListExpensesRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{7}
}

func (x *ListExpensesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListExpensesResponse returns list of expenses
type ListExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expenses      []*Expense             `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesResponse) Reset() {
	*x = ListExpensesResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesResponse) ProtoMessage() {}

func (x *ListExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesResponse.ProtoReflect.Descriptor instead.
func (*ListExpensesResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{8}
}

func (x *ListExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

// GetBalancesRequest gets balances for a user
type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetBalancesResponse returns user balances
type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{10}
}

func (x *GetBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

// SettleBalanceRequest settles a balance between users
type SettleBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleBalanceRequest) Reset() {
	*x = SettleBalanceRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBalanceRequest) ProtoMessage() {}

func (x *SettleBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBalanceRequest.ProtoReflect.Descriptor instead.
func (*SettleBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{11}
}

func (x *SettleBalanceRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SettleBalanceRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SettleBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// SettleBalanceResponse confirms settlement
type SettleBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemainingBalance *Balance               `protobuf:"bytes,3,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SettleBalanceResponse) Reset() {
	*x = SettleBalanceResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBalanceResponse) ProtoMessage() {}

func (x *SettleBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBalanceResponse.ProtoReflect.Descriptor instead.
func (*SettleBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{12}
}

func (x *SettleBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SettleBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SettleBalanceResponse) GetRemainingBalance() *Balance {
	if x != nil {
		return x.RemainingBalance
	}
	return nil
}

// UpdateExpenseRequest updates an expense
type UpdateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseRequest) Reset() {
	*x = UpdateExpenseRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseRequest) ProtoMessage() {}

func (x *UpdateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExpenseRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// UpdateExpenseResponse returns the updated expense
type UpdateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseResponse) Reset() {
	*x = UpdateExpenseResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseResponse) ProtoMessage() {}

func (x *UpdateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

// DeleteExpenseRequest deletes an expense
type DeleteExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_proto_expense_expense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

// DeleteExpenseResponse confirms deletion
type DeleteExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseResponse) Reset() {
	*x = DeleteExpenseResponse{}
	mi := &file_proto_expense_expense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseResponse) ProtoMessage() {}

func (x *DeleteExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_expense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_expense_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteExpenseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_expense_expense_proto protoreflect.FileDescriptor

const file_proto_expense_expense_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/expense/expense.proto\x12\aexpense\"8\n" +
	"\x05Split\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\xf1\x01\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12\x17\n" +
	"\apaid_by\x18\x04 \x01(\tR\x06paidBy\x121\n" +
	"\n" +
	"split_type\x18\x05 \x01(\x0e2\x12.expense.SplitTypeR\tsplitType\x12&\n" +
	"\x06splits\x18\x06 \x03(\v2\x0e.expense.SplitR\x06splits\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"a\n" +
	"\aBalance\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xcf\x01\n" +
	"\x14CreateExpenseRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12\x17\n" +
	"\apaid_by\x18\x03 \x01(\tR\x06paidBy\x121\n" +
	"\n" +
	"split_type\x18\x04 \x01(\x0e2\x12.expense.SplitTypeR\tsplitType\x12&\n" +
	"\x06splits\x18\x05 \x03(\v2\x0e.expense.SplitR\x06splits\"C\n" +
	"\x15CreateExpenseResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"2\n" +
	"\x11GetExpenseRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\"@\n" +
	"\x12GetExpenseResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\".\n" +
	"\x13ListExpensesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x14ListExpensesResponse\x12,\n" +
	"\bexpenses\x18\x01 \x03(\v2\x10.expense.ExpenseR\bexpenses\"-\n" +
	"\x12GetBalancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x13GetBalancesResponse\x12,\n" +
	"\bbalances\x18\x01 \x03(\v2\x10.expense.BalanceR\bbalances\"n\n" +
	"\x14SettleBalanceRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\x8a\x01\n" +
	"\x15SettleBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x11remaining_balance\x18\x03 \x01(\v2\x10.expense.BalanceR\x10remainingBalance\"z\n" +
	"\x14UpdateExpenseRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"C\n" +
	"\x15UpdateExpenseResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"5\n" +
	"\x14DeleteExpenseRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\"K\n" +
	"\x15DeleteExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*1\n" +
	"\tSplitType\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\t\n" +
	"\x05EXACT\x10\x01\x12\x0e\n" +
	"\n" +
	"PERCENTAGE\x10\x022\xae\x04\n" +
	"\x0eExpenseService\x12N\n" +
	"\rCreateExpense\x12\x1d.expense.CreateExpenseRequest\x1a\x1e.expense.CreateExpenseResponse\x12E\n" +
	"\n" +
	"GetExpense\x12\x1a.expense.GetExpenseRequest\x1a\x1b.expense.GetExpenseResponse\x12N\n" +
	"\rUpdateExpense\x12\x1d.expense.UpdateExpenseRequest\x1a\x1e.expense.UpdateExpenseResponse\x12N\n" +
	"\rDeleteExpense\x12\x1d.expense.DeleteExpenseRequest\x1a\x1e.expense.DeleteExpenseResponse\x12K\n" +
	"\fListExpenses\x12\x1c.expense.ListExpensesRequest\x1a\x1d.expense.ListExpensesResponse\x12H\n" +
	"\vGetBalances\x12\x1b.expense.GetBalancesRequest\x1a\x1c.expense.GetBalancesResponse\x12N\n" +
	"\rSettleBalance\x12\x1d.expense.SettleBalanceRequest\x1a\x1e.expense.SettleBalanceResponseB/Z-github.com/vinay/splitwise-grpc/proto/expenseb\x06proto3"

var (
	file_proto_expense_expense_proto_rawDescOnce sync.Once
	file_proto_expense_expense_proto_rawDescData []byte
)

func file_proto_expense_expense_proto_rawDescGZIP() []byte {
	file_proto_expense_expense_proto_rawDescOnce.Do(func() {
		file_proto_expense_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_expense_expense_proto_rawDesc), len(file_proto_expense_expense_proto_rawDesc)))
	})
	return file_proto_expense_expense_proto_rawDescData
}

var file_proto_expense_expense_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_expense_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_expense_expense_proto_goTypes = []any{
	(SplitType)(0),                // 0: expense.SplitType
	(*Split)(nil),                 // 1: expense.Split
	(*Expense)(nil),               // 2: expense.Expense
	(*Balance)(nil),               // 3: expense.Balance
	(*CreateExpenseRequest)(nil),  // 4: expense.CreateExpenseRequest
	(*CreateExpenseResponse)(nil), // 5: expense.CreateExpenseResponse
	(*GetExpenseRequest)(nil),     // 6: expense.GetExpenseRequest
	(*GetExpenseResponse)(nil),    // 7: expense.GetExpenseResponse
	(*ListExpensesRequest)(nil),   // 8: expense.ListExpensesRequest
	(*ListExpensesResponse)(nil),  // 9: expense.ListExpensesResponse
	(*GetBalancesRequest)(nil),    // 10: expense.GetBalancesRequest
	(*GetBalancesResponse)(nil),   // 11: expense.GetBalancesResponse
	(*SettleBalanceRequest)(nil),  // 12: expense.SettleBalanceRequest
	(*SettleBalanceResponse)(nil), // 13: expense.SettleBalanceResponse
	(*UpdateExpenseRequest)(nil),  // 14: expense.UpdateExpenseRequest
	(*UpdateExpenseResponse)(nil), // 15: expense.UpdateExpenseResponse
	(*DeleteExpenseRequest)(nil),  // 16: expense.DeleteExpenseRequest
	(*DeleteExpenseResponse)(nil), // 17: expense.DeleteExpenseResponse
}
var file_proto_expense_expense_proto_depIdxs = []int32{
	0,  // 0: expense.Expense.split_type:type_name -> expense.SplitType
	1,  // 1: expense.Expense.splits:type_name -> expense.Split
	0,  // 2: expense.CreateExpenseRequest.split_type:type_name -> expense.SplitType
	1,  // 3: expense.CreateExpenseRequest.splits:type_name -> expense.Split
	2,  // 4: expense.CreateExpenseResponse.expense:type_name -> expense.Expense
	2,  // 5: expense.GetExpenseResponse.expense:type_name -> expense.Expense
	2,  // 6: expense.ListExpensesResponse.expenses:type_name -> expense.Expense
	3,  // 7: expense.GetBalancesResponse.balances:type_name -> expense.Balance
	3,  // 8: expense.SettleBalanceResponse.remaining_balance:type_name -> expense.Balance
	2,  // 9: expense.UpdateExpenseResponse.expense:type_name -> expense.Expense
	4,  // 10: expense.ExpenseService.CreateExpense:input_type -> expense.CreateExpenseRequest
	6,  // 11: expense.ExpenseService.GetExpense:input_type -> expense.GetExpenseRequest
	14, // 12: expense.ExpenseService.UpdateExpense:input_type -> expense.UpdateExpenseRequest
	16, // 13: expense.ExpenseService.DeleteExpense:input_type -> expense.DeleteExpenseRequest
	8,  // 14: expense.ExpenseService.ListExpenses:input_type -> expense.ListExpensesRequest
	10, // 15: expense.ExpenseService.GetBalances:input_type -> expense.GetBalancesRequest
	12, // 16: expense.ExpenseService.SettleBalance:input_type -> expense.SettleBalanceRequest
	5,  // 17: expense.ExpenseService.CreateExpense:output_type -> expense.CreateExpenseResponse
	7,  // 18: expense.ExpenseService.GetExpense:output_type -> expense.GetExpenseResponse
	15, // 19: expense.ExpenseService.UpdateExpense:output_type -> expense.UpdateExpenseResponse
	17, // 20: expense.ExpenseService.DeleteExpense:output_type -> expense.DeleteExpenseResponse
	9,  // 21: expense.ExpenseService.ListExpenses:output_type -> expense.ListExpensesResponse
	11, // 22: expense.ExpenseService.GetBalances:output_type -> expense.GetBalancesResponse
	13, // 23: expense.ExpenseService.SettleBalance:output_type -> expense.SettleBalanceResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_expense_expense_proto_init() }
func file_proto_expense_expense_proto_init() {
	if File_proto_expense_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_expense_expense_proto_rawDesc), len(file_proto_expense_expense_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_expense_expense_proto_goTypes,
		DependencyIndexes: file_proto_expense_expense_proto_depIdxs,
		EnumInfos:         file_proto_expense_expense_proto_enumTypes,
		MessageInfos:      file_proto_expense_expense_proto_msgTypes,
	}.Build()
	File_proto_expense_expense_proto = out.File
	file_proto_expense_expense_proto_goTypes = nil
	file_proto_expense_expense_proto_depIdxs = nil
}
